### ISSUE TITLE
Generator commands `ets2-villages` and `spritesheet` are missing

### ISSUE THREAD

**Issue by nautofon** [truckermudgeon/maps#26]
I'm trying to get the demo app running locally. I think I managed to do that once before, but that was like a year ago. Following the [readme's suggestions](https://github.com/truckermudgeon/maps?tab=readme-ov-file#generator) on how to run the generator now, I get the following errors.

It looks like `ets2-villages.ts` and `spritesheet.ts` in `packages/clis/generator/commands` are not checked in?

```
$ npx generator map -m usa -i out -o packages/apps/demo/public

node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/Shared/Beauly/maps/packages/clis/generator/commands/ets2-villages' imported from /Users/Shared/Beauly/maps/packages/clis/generator/index.ts
    at finalizeResolution (node:internal/modules/esm/resolve:264:11)
    at moduleResolve (node:internal/modules/esm/resolve:917:10)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at nextResolve (node:internal/modules/esm/hooks:865:28)
    at resolveBase (file:///Users/Shared/Beauly/maps/node_modules/tsx/dist/esm/index.mjs?1732934250597:2:3212)
    at async resolveDirectory (file:///Users/Shared/Beauly/maps/node_modules/tsx/dist/esm/index.mjs?1732934250597:2:3578)
    at async resolve (file:///Users/Shared/Beauly/maps/node_modules/tsx/dist/esm/index.mjs?1732934250597:2:4441)
    at async nextResolve (node:internal/modules/esm/hooks:865:22)
    at async Hooks.resolve (node:internal/modules/esm/hooks:303:24)
    at async handleMessage (node:internal/modules/esm/worker:196:18) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/Shared/Beauly/maps/packages/clis/generator/commands/ets2-villages'
}
```
```
node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/Shared/Beauly/maps/packages/clis/generator/commands/spritesheet' imported from /Users/Shared/Beauly/maps/packages/clis/generator/index.ts
    at finalizeResolution (node:internal/modules/esm/resolve:264:11)
    at moduleResolve (node:internal/modules/esm/resolve:917:10)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at nextResolve (node:internal/modules/esm/hooks:865:28)
    at resolveBase (file:///Users/Shared/Beauly/maps/node_modules/tsx/dist/esm/index.mjs?1732934349108:2:3212)
    at async resolveDirectory (file:///Users/Shared/Beauly/maps/node_modules/tsx/dist/esm/index.mjs?1732934349108:2:3578)
    at async resolve (file:///Users/Shared/Beauly/maps/node_modules/tsx/dist/esm/index.mjs?1732934349108:2:4441)
    at async nextResolve (node:internal/modules/esm/hooks:865:22)
    at async Hooks.resolve (node:internal/modules/esm/hooks:303:24)
    at async handleMessage (node:internal/modules/esm/worker:196:18) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/Shared/Beauly/maps/packages/clis/generator/commands/spritesheet'
}
```

**Comment by nautofon** [comment]
Aha, this is why:
https://github.com/truckermudgeon/maps/blob/b0e31c7dffaa2d8c723969d3422a06f74946cac8/.gitignore#L9-L10

**Comment by truckermudgeon** [comment]
🤦 thanks for the report! Such a rookie mistake on my part 😅

**Comment by nautofon** [comment]
Thanks for the quick fix! 👍

Now the generators run fine, but when trying to start the server, the linter throws an error. Might well be a rookie mistake of my own this time. There is a warning that my TypeScript version is too new, 5.6.2 rather than 5.6.0. Following [a suggestion](https://stackoverflow.com/a/75968104) to upgrade eslint only causes even more errors.

If you happen to have an idea of how I could solve this, I would appreciate it.

```
$ npm start --workspace=packages/apps/demo

> @truckermudgeon/demo-app@0.0.0 start
> vite


  VITE v5.4.8  ready in 272 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.6.0

YOUR TYPESCRIPT VERSION: 5.6.2

Please only submit bug reports when using the officially supported version.

=============
1:38:21 PM [vite] Pre-transform error: Error while loading rule '@typescript-eslint/await-thenable': You have used a rule which requires type information, but don't have parserOptions set to generate type information for this file. See https://typescript-eslint.io/getting-started/typed-linting for enabling linting with type information.
Parser: typescript-eslint/parser
Occurred while linting /Users/Shared/Beauly/maps/packages/apps/demo/src/index.tsx
1:38:21 PM [vite] Pre-transform error: Error while loading rule '@typescript-eslint/await-thenable': You have used a rule which requires type information, but don't have parserOptions set to generate type information for this file. See https://typescript-eslint.io/getting-started/typed-linting for enabling linting with type information.
Parser: typescript-eslint/parser
Occurred while linting /Users/Shared/Beauly/maps/packages/apps/demo/src/index.tsx (x2)
1:38:21 PM [vite] Internal server error: Error while loading rule '@typescript-eslint/await-thenable': You have used a rule which requires type information, but don't have parserOptions set to generate type information for this file. See https://typescript-eslint.io/getting-started/typed-linting for enabling linting with type information.
Parser: typescript-eslint/parser
Occurred while linting /Users/Shared/Beauly/maps/packages/apps/demo/src/index.tsx
  Plugin: vite-plugin-eslint
  File: /Users/Shared/Beauly/maps/packages/apps/demo/src/index.tsx
      at TransformPluginContext._formatError (file:///Users/Shared/Beauly/maps/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:49193:41)
      at TransformPluginContext.error (file:///Users/Shared/Beauly/maps/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:49188:16)
      at TransformPluginContext.transform (file:///Users/Shared/Beauly/maps/node_modules/vite-plugin-eslint/dist/index.mjs:1:1989)
      at async PluginContainer.transform (file:///Users/Shared/Beauly/maps/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:49034:18)
      at async loadAndTransform (file:///Users/Shared/Beauly/maps/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:51867:27)
      at async viteTransformMiddleware (file:///Users/Shared/Beauly/maps/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:61824:24)
```

**Comment by truckermudgeon** [comment]
Hmmmm... I'll have to spend more time digging into this tomorrow 😔. Sorry for the trouble!

Here's what I know so far:
* I'm also using TypeScript 5.6.2, and things work for me out of my regular dev directory
* If I try to clone the `maps` repo into a clean directory and run the `demo` app, I get a totally different set of errors:

```
$ npm start --workspace=packages/apps/demo                                   

> @truckermudgeon/demo-app@0.0.0 start
> vite


  VITE v5.4.8  ready in 485 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.6.0

YOUR TYPESCRIPT VERSION: 5.6.2

Please only submit bug reports when using the officially supported version.

=============
8:36:42 AM [vite] Pre-transform error: 
/Users/tmudge/dev/test/packages/apps/demo/src/index.tsx
  0:0  error  Parsing error: ESLint was configured to run on `/Users/tmudge/dev/test/packages/apps/demo/src/index.tsx` using `parserOptions.project`:
- <tsconfigRootDir>/packages/apis/navigation/tsconfig.json
- <tsconfigRootDir>/packages/apis/telemetry/tsconfig.json
- <tsconfigRootDir>/packages/apps/demo/tsconfig.json
- <tsconfigRootDir>/packages/apps/prefabs/tsconfig.json
- <tsconfigRootDir>/packages/clis/generator/tsconfig.json
- <tsconfigRootDir>/packages/clis/parser/tsconfig.json
- <tsconfigRootDir>/packages/libs/api/tsconfig.json
- <tsconfigRootDir>/packages/libs/base/tsconfig.json
- <tsconfigRootDir>/packages/libs/map/tsconfig.json
- <tsconfigRootDir>/packages/libs/ui/tsconfig.json
However, none of those TSConfigs include this file. Either:
- Change ESLint's list of included files to not include this file
- Change one of those TSConfigs to include this file
- Create a new TSConfig that includes this file and include it in your parserOptions.project
See the typescript-eslint docs for more info: https://typescript-eslint.io/troubleshooting/typed-linting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file

✖ 1 problem (1 error, 0 warnings)

**Comment by truckermudgeon** [comment]
In the meantime, you can disable the eslint plugin by editing:

```diff
diff --git a/packages/apps/demo/vite.config.ts b/packages/apps/demo/vite.config.ts
index d6f39a0..2492a07 100644
--- a/packages/apps/demo/vite.config.ts
+++ b/packages/apps/demo/vite.config.ts
@@ -11,7 +11,7 @@ export default defineConfig(() => {
     server: {
       open: true,
     },
-    plugins: [react(), viteTsconfigPaths(), eslint()],
+    plugins: [react(), viteTsconfigPaths()],
     test: {
       globals: true,
       environment: 'jsdom',
```

and that should get the `demo` app running.

**Comment by nautofon** [comment]
Yep, the patch got the demo working. Thank you!
